### ISSUE TITLE
Lab3-4 Замечания

### ISSUE THREAD

**Issue by Andrewbooq** [petchenn/PP3#1]
Как пишут разработчики Microsoft:

![image](https://github.com/user-attachments/assets/f2ff41fb-1099-4529-af6a-85c0c976e54b)

источник https://learn.microsoft.com/ru-ru/windows/win32/api/processthreadsapi/nf-processthreadsapi-createthread

**Comment by petchenn** [comment]
Я добавила всё, что было в предыдущей лабе, кроме возврата id потока.  Оно даже работает.

**Comment by Andrewbooq** [comment]
Странно, к меня нет. Посмотри пожалуйста, что ты всё запушила в репозиторий.
![image](https://github.com/user-attachments/assets/26d329b1-9f0c-4380-84cb-dbc9dbcbf718)

**Comment by petchenn** [comment]
На сайте, когда я смотрю, всё на месте. Не знаю, в чём проблема. Могу просто ещё раз весь код посредством копировать-вставить залить.

**Comment by petchenn** [comment]
Вы правы, я клонировала репозиторий и у меня теперь тоже не работает. Сейчас буду исправлять.

**Comment by petchenn** [comment]
Исправила.

**Comment by Andrewbooq** [comment]
Да, всё отлично, запускается, ошибки проверяются.
Делай дальше
```
#ifdef _WIN32
    HANDLE thread = (HANDLE)_beginthreadex(...
#elif __linux__
    int err = pthread_create(...
#endif
....
```
Можешь сдать отдельно 3 Лабу по WinAPI, а можешь допилить POSIX часть и сдать всё сразу.

**Comment by Andrewbooq** [comment]
Альбина, залей свой код, что есть, я посмотрю. Нам надо с тобой до 30 с лабой разобраться. Чтобы ты сдала зачёт в этом году.

**Comment by petchenn** [comment]
Залила

**Comment by Andrewbooq** [comment]
У тебя putFunc должна быть в public секции в классе, после этого в винде начинает собираться и правильно работать. Для линукса, как-будто скопировала у кого-то из девченок, и не поправила. там и std:: пропущен, и тип unsigned int нужно использовать, а не double, и параметров у тебя один, а не два...
для sqrt в линукс надо добавтьи include <math.h>

**Comment by Andrewbooq** [comment]
Завтра на зачет приходи. Всё с лабой ясно, если успеешь - поправь, если нет, лучше к зачету готовься.
Лаба в принципе правильная, надо только очевидные вещи поправить. Но я буду без ноутбука, смотреть уже некогда.
В твоём случае можно с таким результатом приходить.

**Comment by petchenn** [comment]
Хорошо, спасибо. Там немного править, доделаю.
